spring.application.name=gamestore

# ============================================================
# BANCO ORACLE FIAP
# Troque pelo seu RM e senha fornecidos pela faculdade
# ============================================================
spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
spring.datasource.username=pf0392
spring.datasource.password=izumi25
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Porta do servidor
server.port=8080
